export const fileMap = {
  'BUNKER': 'bunker',
  'CENTER': 'center',
  'CHICKEN_UNIVERSE': 'hab_chicken_universe',
  'COOP': 'coop',
  'DOUBLE_DECKER': 'double_decker',
  'EGGKEA': 'eggkea',
  'EGGTOPIA': 'hab_eggtopia',
  'HAB_10K': 'hab_10k',
  'HAB_1K': 'hab_1k',
  'HANGAR': 'hanger',
  'LONG_HOUSE': 'long_house',
  'MONOLITH': 'hab_monolith',
  'PLANET_PORTAL': 'hab_portal',
  'SHACK': 'shack',
  'SHORT_HOUSE': 'short_house',
  'SUPER_SHACK': 'super_shack',
  'THE_STANDARD': 'the_standard',
  'TOWER': 'tower',
  'WAREHOUSE': 'warehouse',
  'SILO_0_LARGE': 'ei_silo_0_large',
  'SILO_0_MED': 'ei_silo_0_med',
  'SILO_0_SMALL': 'ei_silo_0_small',
  'SILO_1_LARGE': 'ei_silo_1_large',
  'SILO_1_MED': 'ei_silo_1_med',
  'SILO_1_SMALL': 'ei_silo_1_small',
  'HATCHERY_AI': 'ei_hatchery_ai',
  'HATCHERY_AI_TOP_1': 'ei_hatchery_ai_top_0',
  'HATCHERY_AI_TOP_2': 'ei_hatchery_ai_top_1',
  'HATCHERY_AI_TOP_3': 'ei_hatchery_ai_top_2',
  'HATCHERY_AI_TOP_4': 'ei_hatchery_ai_top_3',
  'HATCHERY_ANTIMATTER': 'ei_hatchery_antimatter',
  'HATCHERY_DARK_MATTER': 'ei_hatchery_darkmatter',
  'HATCHERY_DARK_MATTER_RING_1': 'ei_hatchery_darkmatter_ring_1',
  'HATCHERY_DARK_MATTER_RING_2': 'ei_hatchery_darkmatter_ring_2',
  'HATCHERY_DARK_MATTER_RING_3': 'ei_hatchery_darkmatter_ring_3',
  'HATCHERY_DILITHIUM': 'ei_hatchery_dilithium',
  'HATCHERY_EDIBLE': 'ei_hatchery_edible',
  'HATCHERY_ENLIGHTENMENT': 'ei_hatchery_enlightenment',
  'HATCHERY_ENLIGHTENMENT_ORB': 'ei_hatchery_enlightenment_orb',
  'HATCHERY_FUSION': 'ei_hatchery_fusion',
  'HATCHERY_GRAVITON': 'ei_hatchery_graviton',
  'HATCHERY_GRAVITON_TOP': 'ei_hatchery_graviton_top',
  'HATCHERY_IMMORTALITY': 'ei_hatchery_immortality',
  'HATCHERY_MEDICAL': 'ei_hatchery_medical',
  'HATCHERY_NEBULA': 'ei_hatchery_vision',
  'HATCHERY_NEBULA_MIDDLE': 'ei_hatchery_vision_middle',
  'HATCHERY_NEBULA_TOP': 'ei_hatchery_vision_top',
  'HATCHERY_PRODIGY': 'ei_hatchery_prodigy',
  'HATCHERY_QUANTUM': 'ei_hatchery_quantum',
  'HATCHERY_ROCKET_FUEL': 'ei_hatchery_rocketfuel',
  'HATCHERY_SUPERFOOD': 'ei_hatchery_superfood',
  'HATCHERY_SUPERMATERIAL': 'ei_hatchery_supermaterial',
  'HATCHERY_TACHYON': 'ei_hatchery_tachyon',
  'HATCHERY_TERRAFORM': 'ei_hatchery_terraform',
  'HATCHERY_UNIVERSE': 'ei_hatchery_universe',
  'HATCHERY_UNIVERSE_PROBE': 'ei_hatchery_universe_probe',
  'MISSION_CONTROL_1': 'ei_mission_control_1',
  'MISSION_CONTROL_2': 'ei_mission_control_2',
  'MISSION_CONTROL_3': 'ei_mission_control_3',
  'DEPOT_1': 'ei_depot_1',
  'DEPOT_2': 'ei_depot_2',
  'DEPOT_3': 'ei_depot_3',
  'DEPOT_4': 'ei_depot_4',
  'DEPOT_5': 'ei_depot_5',
  'DEPOT_6': 'ei_depot_6',
  'DEPOT_7': 'ei_depot_7',
  'FUEL_TANK_1': 'ei_fuel_tank_1',
  'FUEL_TANK_2': 'ei_fuel_tank_2',
  'FUEL_TANK_3': 'ei_fuel_tank_3',
  'FUEL_TANK_4': 'ei_fuel_tank_4',
  'HOA_1': 'ei_hoa_1',
  'HOA_2': 'ei_hoa_2',
  'HOA_3': 'ei_hoa_3',
  'LAB_1': 'ei_lab_1',
  'LAB_2': 'ei_lab_2',
  'LAB_3': 'ei_lab_3',
  'LAB_4': 'ei_lab_4',
  'LAB_5': 'ei_lab_5',
  'LAB_6': 'ei_lab_6',
  'MAILBOX': 'ei_farm_mailbox_empty',
  'HARDSCAPE': 'ei_farm_hardscape',
  'GROUND': 'ei_farm_ground',
  'HYPERLOOP_TRACK': 'ei_hyperloop_track',
  'HYPERLOOP_STOP': 'ei_hyperloop_stop',
  'TROPHY_CASE': 'ei_trophy_case2',
}

export const categoryMap = {
  'BUNKER': 'HAB',
  'CENTER': 'HAB',
  'CHICKEN_UNIVERSE': 'HAB',
  'COOP': 'HAB',
  'DOUBLE_DECKER': 'HAB',
  'EGGKEA': 'HAB',
  'EGGTOPIA': 'HAB',
  'HAB_10K': 'HAB',
  'HAB_1K': 'HAB',
  'HANGAR': 'HAB',
  'LONG_HOUSE': 'HAB',
  'MONOLITH': 'HAB',
  'PLANET_PORTAL': 'HAB',
  'SHACK': 'HAB',
  'SHORT_HOUSE': 'HAB',
  'SUPER_SHACK': 'HAB',
  'THE_STANDARD': 'HAB',
  'TOWER': 'HAB',
  'WAREHOUSE': 'HAB',
  'SILO_0_LARGE': 'SILO',
  'SILO_0_MED': 'SILO',
  'SILO_0_SMALL': 'SILO',
  'SILO_1_LARGE': 'SILO',
  'SILO_1_MED': 'SILO',
  'SILO_1_SMALL': 'SILO',
  'HATCHERY_AI': 'HATCHERY',
  'HATCHERY_AI_TOP_1': 'HATCHERY_PART',
  'HATCHERY_AI_TOP_2': 'HATCHERY_PART',
  'HATCHERY_AI_TOP_3': 'HATCHERY_PART',
  'HATCHERY_AI_TOP_4': 'HATCHERY_PART',
  'HATCHERY_ANTIMATTER': 'HATCHERY',
  'HATCHERY_DARK_MATTER': 'HATCHERY',
  'HATCHERY_DARK_MATTER_RING_1': 'HATCHERY_PART',
  'HATCHERY_DARK_MATTER_RING_2': 'HATCHERY_PART',
  'HATCHERY_DARK_MATTER_RING_3': 'HATCHERY_PART',
  'HATCHERY_DILITHIUM': 'HATCHERY',
  'HATCHERY_EDIBLE': 'HATCHERY',
  'HATCHERY_ENLIGHTENMENT': 'HATCHERY',
  'HATCHERY_ENLIGHTENMENT_ORB': 'HATCHERY_PART',
  'HATCHERY_FUSION': 'HATCHERY',
  'HATCHERY_GRAVITON': 'HATCHERY',
  'HATCHERY_GRAVITON_TOP': 'HATCHERY_PART',
  'HATCHERY_IMMORTALITY': 'HATCHERY',
  'HATCHERY_MEDICAL': 'HATCHERY',
  'HATCHERY_NEBULA': 'HATCHERY',
  'HATCHERY_NEBULA_MIDDLE': 'HATCHERY_PART',
  'HATCHERY_NEBULA_TOP': 'HATCHERY_PART',
  'HATCHERY_PRODIGY': 'HATCHERY',
  'HATCHERY_QUANTUM': 'HATCHERY',
  'HATCHERY_ROCKET_FUEL': 'HATCHERY',
  'HATCHERY_SUPERFOOD': 'HATCHERY',
  'HATCHERY_SUPERMATERIAL': 'HATCHERY',
  'HATCHERY_TACHYON': 'HATCHERY',
  'HATCHERY_TERRAFORM': 'HATCHERY',
  'HATCHERY_UNIVERSE': 'HATCHERY',
  'HATCHERY_UNIVERSE_PROBE': 'HATCHERY_PART',
  'MISSION_CONTROL_1': 'MISSION_CONTROL',
  'MISSION_CONTROL_2': 'MISSION_CONTROL',
  'MISSION_CONTROL_3': 'MISSION_CONTROL',
  'DEPOT_1': 'SHIPPING_DEPOT',
  'DEPOT_2': 'SHIPPING_DEPOT',
  'DEPOT_3': 'SHIPPING_DEPOT',
  'DEPOT_4': 'SHIPPING_DEPOT',
  'DEPOT_5': 'SHIPPING_DEPOT',
  'DEPOT_6': 'SHIPPING_DEPOT',
  'DEPOT_7': 'SHIPPING_DEPOT',
  'FUEL_TANK_1': 'FUEL_TANK',
  'FUEL_TANK_2': 'FUEL_TANK',
  'FUEL_TANK_3': 'FUEL_TANK',
  'FUEL_TANK_4': 'FUEL_TANK',
  'HOA_1': 'HOA',
  'HOA_2': 'HOA',
  'HOA_3': 'HOA',
  'LAB_1': 'LAB',
  'LAB_2': 'LAB',
  'LAB_3': 'LAB',
  'LAB_4': 'LAB',
  'LAB_5': 'LAB',
  'LAB_6': 'LAB',
  'MAILBOX': 'MAILBOX',
  'HARDSCAPE': 'HARDSCAPE',
  'GROUND': 'GROUND',
  'HYPERLOOP_TRACK': 'HYPERLOOP_TRACK',
  'HYPERLOOP_STOP': 'HYPERLOOP_STOP',
  'TROPHY_CASE': 'TROPHY_CASE',
}

export const defaults = {
  max: [
    'CHICKEN_UNIVERSE',
    'CHICKEN_UNIVERSE',
    'CHICKEN_UNIVERSE',
    'CHICKEN_UNIVERSE',
    'HATCHERY_ENLIGHTENMENT',
    'SILO_1_LARGE',
    'SILO_1_LARGE',
    'SILO_1_LARGE',
    'SILO_1_LARGE',
    'SILO_1_LARGE',
    'SILO_1_LARGE',
    'SILO_1_LARGE',
    'SILO_1_LARGE',
    'SILO_1_LARGE',
    'SILO_1_LARGE',
    'DEPOT_1',
    'FUEL_TANK_4',
    'HOA_3',
    'MISSION_CONTROL_3',
    'LAB_6',
    'MAILBOX',
    'GROUND',
    'HARDSCAPE',
    'HYPERLOOP_TRACK',
    'HYPERLOOP_STOP',
    'TROPHY_CASE'
  ],
  new: [
    'COOP',
    'HATCHERY_EDIBLE',
    'SILO_1_LARGE',
    'DEPOT_1',
    'FUEL_TANK_4',
    'HOA_3',
    'MISSION_CONTROL_3',
    'LAB_1',
    'MAILBOX',
    'GROUND',
    'HARDSCAPE',
    'HYPERLOOP_TRACK',
    'HYPERLOOP_STOP',
    'TROPHY_CASE'
  ]
}

export const available = defaults.max.map(building => categoryMap[building]);

export const displayNames = {
  'HAB': 'Habs',
  'GROUND': 'Ground',
  'HARDSCAPE': 'Hardscape',
  'HATCHERY': 'Hatchery',
  'MISSION_CONTROL': 'Launchpad',
  'SHIPPING_DEPOT': 'Shipping Depot',
  'FUEL_TANK': 'Fuel Tank',
  'HOA': 'Hall of Artifacts',
  'LAB': 'Research Center',
  'MAILBOX': 'Mailbox',
  'HYPERLOOP_STOP': 'Hyperloop Station',
  'TROPHY_CASE': 'Trophy Case',
  'SILO': 'Silo'
}


export const dependentBuildings = {
  'LAB': 'HOA',
  'HATCHERY': 'MISSION_CONTROL',
  'DEPOT': 'MISSION_CONTROL',
  'MISSION_CONTROL': 'FUEL_TANK'
}

export const URLs = {
  config: 'https://gist.githubusercontent.com/tylertms/714615bbf3fa3ebb315d7fd554f2a699/raw',
  worker: 'https://shell.tylertms.workers.dev/',
  r2: 'https://pub-09894c58859248c6ba3cd24f4045b4b5.r2.dev/',
};